version: '3.8'

services:
  # BACKEND (Aimeos Engine)
  backend:
    build:
      context: ./aimeos-headless
      dockerfile: Dockerfile
    container_name: nexus-backend
    volumes:
      - ./aimeos-headless:/var/www
    networks:
      - sinacsis-net

  # FRONTEND (Vue.js 3 Dev Server)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexus-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita conflictos de dependencias locales/contenedor
    networks:
      - sinacsis-net

  # BASE DE DATOS
  db:
    image: postgres:15-alpine
    container_name: nexus-db
    environment:
      POSTGRES_DB: nexus_gear
      POSTGRES_USER: sinacsis_admin
      POSTGRES_PASSWORD: your_secure_password
    networks:
      - sinacsis-net

networks:
  sinacsis-net:
    driver: bridge
